language: elixir
elixir:
  - 1.3.1
  - 1.2.6
otp_release:
  - 19.0
  - 18.3
  - 18.2
before_install:
  - mix local.rebar --force
before_script:
  - epmd -daemon
script:
  - mix cachex credo --all --format=oneline
  - mix cachex coveralls.travis --trace
branches:
  only:
    - master
env:
  - MIX_ENV=test
