language: elixir
elixir:
  - 1.2.5
otp_release:
  - 18.3
  - 18.2
  - 18.1
  - 18.0
before_script:
  - epmd -daemon
script:
  - mix cachex.analyze
  - mix cachex.coveralls.travis --trace
branches:
  only:
    - master
