language: elixir
elixir:
  - 1.3.2
  - 1.2.6
otp_release:
  - 19.0
  - 18.3
before_install:
  - mix local.rebar --force
before_script:
  - epmd -daemon
script:
  - mix credo --all --format=oneline && mix coveralls --trace
branches:
  only:
    - master
env:
  - MIX_ENV=test
