language: elixir
elixir:
  - 1.2.4
otp_release:
  - 18.2
  - 18.1
  - 18.0
before_script:
  - epmd -daemon
script:
  - mix cachex.test --trace
after_success:
  - mix cachex.coveralls.travis
branches:
  only:
    - master
